"""
Demo data for SyntaAI ERP Security MCP Server.
Simulates realistic SAP security findings for demonstration and testing.
Replace with real OData calls when SAP CAL instance is ready.
"""

from datetime import datetime, timedelta

# ============================================================
# Users
# ============================================================

DEMO_USERS = [
    {
        "username": "ADMIN01",
        "full_name": "System Administrator",
        "email": "admin01@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2019-03-15",
        "last_login": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d"),
        "days_since_login": 1,
        "department": "IT Basis",
        "roles": ["Z_BASIS_ADMIN", "Z_USER_ADMIN", "Z_TRANSPORT_ADMIN"],
        "profiles": ["SAP_ALL"],
        "has_debug_auth": True,
        "default_password": False,
    },
    {
        "username": "ADMIN02",
        "full_name": "Backup Administrator",
        "email": "admin02@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2019-03-15",
        "last_login": (datetime.now() - timedelta(days=120)).strftime("%Y-%m-%d"),
        "days_since_login": 120,
        "department": "IT Basis",
        "roles": ["Z_BASIS_ADMIN", "Z_USER_ADMIN"],
        "profiles": ["SAP_ALL"],
        "has_debug_auth": True,
        "default_password": False,
    },
    {
        "username": "EMERGENCY",
        "full_name": "Emergency Access Account",
        "email": "emergency@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2020-01-10",
        "last_login": (datetime.now() - timedelta(days=200)).strftime("%Y-%m-%d"),
        "days_since_login": 200,
        "department": "IT Security",
        "roles": ["Z_EMERGENCY_ACCESS"],
        "profiles": ["SAP_ALL"],
        "has_debug_auth": True,
        "default_password": True,
    },
    {
        "username": "J.SMITH",
        "full_name": "John Smith",
        "email": "j.smith@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2021-06-01",
        "last_login": (datetime.now() - timedelta(days=2)).strftime("%Y-%m-%d"),
        "days_since_login": 2,
        "department": "Finance",
        "roles": ["Z_FI_ACCOUNTS_PAYABLE", "Z_FI_ACCOUNTS_RECEIVABLE", "Z_FI_PAYMENT_RUN"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "M.JONES",
        "full_name": "Mary Jones",
        "email": "m.jones@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2020-09-15",
        "last_login": (datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d"),
        "days_since_login": 3,
        "department": "Finance",
        "roles": ["Z_FI_ACCOUNTS_PAYABLE", "Z_FI_GL_POSTING"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "R.KUMAR",
        "full_name": "Raj Kumar",
        "email": "r.kumar@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2022-01-20",
        "last_login": (datetime.now() - timedelta(days=5)).strftime("%Y-%m-%d"),
        "days_since_login": 5,
        "department": "Procurement",
        "roles": ["Z_MM_PURCHASER", "Z_MM_PURCHASE_APPROVE", "Z_MM_GOODS_RECEIPT"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "S.WILSON",
        "full_name": "Sarah Wilson",
        "email": "s.wilson@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2021-03-10",
        "last_login": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d"),
        "days_since_login": 1,
        "department": "HR",
        "roles": ["Z_HR_ADMIN", "Z_HR_PAYROLL"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "T.GARCIA",
        "full_name": "Tom Garcia",
        "email": "t.garcia@demo.com",
        "user_type": "Dialog",
        "status": "Locked",
        "created_date": "2020-11-05",
        "last_login": (datetime.now() - timedelta(days=180)).strftime("%Y-%m-%d"),
        "days_since_login": 180,
        "department": "Finance",
        "roles": ["Z_FI_GL_POSTING", "Z_FI_ASSET_MGMT"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "L.CHEN",
        "full_name": "Lisa Chen",
        "email": "l.chen@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2023-02-14",
        "last_login": (datetime.now() - timedelta(days=95)).strftime("%Y-%m-%d"),
        "days_since_login": 95,
        "department": "IT Development",
        "roles": ["Z_DEV_ABAP", "Z_DEV_TRANSPORT"],
        "profiles": ["SAP_NEW"],
        "has_debug_auth": True,
        "default_password": False,
    },
    {
        "username": "D.BROWN",
        "full_name": "David Brown",
        "email": "d.brown@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2021-08-22",
        "last_login": (datetime.now() - timedelta(days=150)).strftime("%Y-%m-%d"),
        "days_since_login": 150,
        "department": "Sales",
        "roles": ["Z_SD_SALES_ORDER", "Z_SD_BILLING"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": True,
    },
    {
        "username": "A.PATEL",
        "full_name": "Anita Patel",
        "email": "a.patel@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2022-05-30",
        "last_login": (datetime.now() - timedelta(days=10)).strftime("%Y-%m-%d"),
        "days_since_login": 10,
        "department": "Controlling",
        "roles": ["Z_CO_COST_CENTER", "Z_CO_PROFIT_CENTER", "Z_FI_GL_POSTING"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "RFC_FICO",
        "full_name": "RFC Interface - FICO",
        "email": "rfc_fico@demo.com",
        "user_type": "Communication",
        "status": "Active",
        "created_date": "2019-06-01",
        "last_login": (datetime.now() - timedelta(days=0)).strftime("%Y-%m-%d"),
        "days_since_login": 0,
        "department": "IT Interfaces",
        "roles": ["Z_RFC_FICO_READ", "Z_RFC_FICO_WRITE"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "BATCH_USER",
        "full_name": "Batch Processing User",
        "email": "batch@demo.com",
        "user_type": "System",
        "status": "Active",
        "created_date": "2019-03-15",
        "last_login": (datetime.now() - timedelta(days=0)).strftime("%Y-%m-%d"),
        "days_since_login": 0,
        "department": "IT Operations",
        "roles": ["Z_BATCH_FI", "Z_BATCH_MM", "Z_BATCH_SD"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "SVC_PORTAL",
        "full_name": "Portal Service Account",
        "email": "portal@demo.com",
        "user_type": "Service",
        "status": "Active",
        "created_date": "2020-04-20",
        "last_login": (datetime.now() - timedelta(days=0)).strftime("%Y-%m-%d"),
        "days_since_login": 0,
        "department": "IT Portal",
        "roles": ["Z_PORTAL_ACCESS", "Z_ESS_MSS"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "K.NAKAMURA",
        "full_name": "Kenji Nakamura",
        "email": "k.nakamura@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2023-07-01",
        "last_login": (datetime.now() - timedelta(days=130)).strftime("%Y-%m-%d"),
        "days_since_login": 130,
        "department": "Warehouse",
        "roles": ["Z_WM_WAREHOUSE_MGMT"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": True,
    },
    {
        "username": "P.MUELLER",
        "full_name": "Peter Mueller",
        "email": "p.mueller@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2022-11-10",
        "last_login": (datetime.now() - timedelta(days=4)).strftime("%Y-%m-%d"),
        "days_since_login": 4,
        "department": "IT Security",
        "roles": ["Z_SEC_ADMIN", "Z_GRC_MANAGER"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "N.SILVA",
        "full_name": "Nina Silva",
        "email": "n.silva@demo.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2024-01-15",
        "last_login": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"),
        "days_since_login": 7,
        "department": "Finance",
        "roles": ["Z_FI_ACCOUNTS_PAYABLE"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": False,
    },
    {
        "username": "OLD_VENDOR",
        "full_name": "Legacy Vendor Account",
        "email": "vendor@external.com",
        "user_type": "Dialog",
        "status": "Active",
        "created_date": "2018-05-01",
        "last_login": (datetime.now() - timedelta(days=365)).strftime("%Y-%m-%d"),
        "days_since_login": 365,
        "department": "External",
        "roles": ["Z_MM_VENDOR_PORTAL", "Z_MM_PURCHASER"],
        "profiles": [],
        "has_debug_auth": False,
        "default_password": True,
    },
]


# ============================================================
# Roles
# ============================================================

DEMO_ROLES = [
    {"role_name": "Z_BASIS_ADMIN", "description": "Basis Administration", "type": "Single", "user_count": 2, "critical": True,
     "authorizations": ["S_ADMI_FCD", "S_BTCH_ADM", "S_RZL_ADM", "S_TABU_DIS"]},
    {"role_name": "Z_USER_ADMIN", "description": "User Administration", "type": "Single", "user_count": 2, "critical": True,
     "authorizations": ["S_USER_GRP", "S_USER_PRO", "S_USER_AUT"]},
    {"role_name": "Z_TRANSPORT_ADMIN", "description": "Transport Management", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["S_CTS_ADMI", "S_TRANSPRT"]},
    {"role_name": "Z_FI_ACCOUNTS_PAYABLE", "description": "Accounts Payable Processing", "type": "Single", "user_count": 3, "critical": False,
     "authorizations": ["F_BKPF_BUK", "F_BKPF_BLA", "F_LFA1_BUK"]},
    {"role_name": "Z_FI_ACCOUNTS_RECEIVABLE", "description": "Accounts Receivable Processing", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["F_BKPF_BUK", "F_KNA1_BUK"]},
    {"role_name": "Z_FI_PAYMENT_RUN", "description": "Payment Run Execution", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["F_REGU_BUK", "F_BKPF_BUK"]},
    {"role_name": "Z_FI_GL_POSTING", "description": "General Ledger Posting", "type": "Single", "user_count": 3, "critical": False,
     "authorizations": ["F_BKPF_BUK", "F_BKPF_BLA", "F_BKPF_KOA"]},
    {"role_name": "Z_FI_ASSET_MGMT", "description": "Asset Management", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["A_ABGANG", "A_ZUGANG"]},
    {"role_name": "Z_MM_PURCHASER", "description": "Purchase Order Processing", "type": "Single", "user_count": 2, "critical": False,
     "authorizations": ["M_BEST_BSA", "M_BEST_EKG", "M_BEST_WRK"]},
    {"role_name": "Z_MM_PURCHASE_APPROVE", "description": "Purchase Order Approval", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["M_BEST_BSA", "M_EINK_FRG"]},
    {"role_name": "Z_MM_GOODS_RECEIPT", "description": "Goods Receipt Processing", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["M_MSEG_BWA", "M_MSEG_WMB"]},
    {"role_name": "Z_HR_ADMIN", "description": "HR Master Data Administration", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["P_ORGIN", "P_PERNR", "PLOG"]},
    {"role_name": "Z_HR_PAYROLL", "description": "Payroll Processing", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["P_ORGIN", "P_ABAP", "S_PROGRAM"]},
    {"role_name": "Z_SD_SALES_ORDER", "description": "Sales Order Processing", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["V_VBAK_VKO", "V_VBAK_AAT"]},
    {"role_name": "Z_SD_BILLING", "description": "Billing Document Processing", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["V_VBRK_VKO", "V_VBRK_FKA"]},
    {"role_name": "Z_DEV_ABAP", "description": "ABAP Development", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["S_DEVELOP", "S_PROGRAM", "S_DEBUG"]},
    {"role_name": "Z_DEV_TRANSPORT", "description": "Development Transport", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_CTS_ADMI", "S_TRANSPRT"]},
    {"role_name": "Z_SEC_ADMIN", "description": "Security Administration", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["S_USER_GRP", "S_USER_PRO", "S_SECR_ADM"]},
    {"role_name": "Z_GRC_MANAGER", "description": "GRC Risk Management", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["GRFN_ROLE", "GRFN_CC"]},
    {"role_name": "Z_EMERGENCY_ACCESS", "description": "Emergency Firefighter Access", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["S_ADMI_FCD", "S_USER_GRP", "S_TABU_DIS", "S_DEBUG"]},
    {"role_name": "Z_CO_COST_CENTER", "description": "Cost Center Accounting", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["K_CSKB", "K_CSKS"]},
    {"role_name": "Z_CO_PROFIT_CENTER", "description": "Profit Center Accounting", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["K_PCA", "K_PCAP"]},
    {"role_name": "Z_WM_WAREHOUSE_MGMT", "description": "Warehouse Management", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["L_TCODE", "L_LGNUM"]},
    {"role_name": "Z_PORTAL_ACCESS", "description": "Portal Service Access", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_ICF"]},
    {"role_name": "Z_ESS_MSS", "description": "Employee/Manager Self-Service", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["P_ORGIN", "PLOG"]},
    {"role_name": "Z_MM_VENDOR_PORTAL", "description": "Vendor Portal Access", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["M_BEST_BSA"]},
    {"role_name": "Z_RFC_FICO_READ", "description": "RFC Interface FI/CO Read", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_RFC", "F_BKPF_BUK"]},
    {"role_name": "Z_RFC_FICO_WRITE", "description": "RFC Interface FI/CO Write", "type": "Single", "user_count": 1, "critical": True,
     "authorizations": ["S_RFC", "F_BKPF_BUK", "F_BKPF_BLA"]},
    {"role_name": "Z_BATCH_FI", "description": "Batch Processing Finance", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_BTCH_JOB", "F_BKPF_BUK"]},
    {"role_name": "Z_BATCH_MM", "description": "Batch Processing Materials", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_BTCH_JOB", "M_BEST_BSA"]},
    {"role_name": "Z_BATCH_SD", "description": "Batch Processing Sales", "type": "Single", "user_count": 1, "critical": False,
     "authorizations": ["S_BTCH_JOB", "V_VBAK_VKO"]},
]


# ============================================================
# Security Parameters
# ============================================================

DEMO_SECURITY_PARAMS = [
    {"parameter": "login/min_password_lng", "current_value": "6", "recommended_value": "12", "description": "Minimum password length", "compliant": False},
    {"parameter": "login/password_expiration_time", "current_value": "90", "recommended_value": "90", "description": "Password expiration in days", "compliant": True},
    {"parameter": "login/fails_to_user_lock", "current_value": "5", "recommended_value": "5", "description": "Failed login attempts before lock", "compliant": True},
    {"parameter": "login/failed_user_auto_unlock", "current_value": "1", "recommended_value": "0", "description": "Auto-unlock after failed logins (0=no auto unlock)", "compliant": False},
    {"parameter": "login/password_history_size", "current_value": "5", "recommended_value": "12", "description": "Number of previous passwords remembered", "compliant": False},
    {"parameter": "login/min_password_uppercase", "current_value": "0", "recommended_value": "1", "description": "Minimum uppercase characters", "compliant": False},
    {"parameter": "login/min_password_lowercase", "current_value": "0", "recommended_value": "1", "description": "Minimum lowercase characters", "compliant": False},
    {"parameter": "login/min_password_specials", "current_value": "0", "recommended_value": "1", "description": "Minimum special characters", "compliant": False},
    {"parameter": "login/min_password_digits", "current_value": "1", "recommended_value": "1", "description": "Minimum digit characters", "compliant": True},
    {"parameter": "rfc/reject_expired_passwd", "current_value": "1", "recommended_value": "1", "description": "Reject RFC calls with expired password", "compliant": True},
    {"parameter": "login/no_automatic_user_sapstar", "current_value": "1", "recommended_value": "1", "description": "Disable automatic SAP* user", "compliant": True},
    {"parameter": "login/password_compliance_to_current_policy", "current_value": "0", "recommended_value": "1", "description": "Force compliance with current password policy", "compliant": False},
    {"parameter": "rec/client", "current_value": "ALL", "recommended_value": "ALL", "description": "Security audit log recording client", "compliant": True},
    {"parameter": "rsau/enable", "current_value": "1", "recommended_value": "1", "description": "Enable security audit log", "compliant": True},
    {"parameter": "login/disable_multi_gui_login", "current_value": "0", "recommended_value": "1", "description": "Prevent multiple GUI sessions", "compliant": False},
    {"parameter": "icf/set_HTTPonly_flag_on_cookies", "current_value": "3", "recommended_value": "3", "description": "HTTPOnly flag on cookies", "compliant": True},
    {"parameter": "login/create_sso2_ticket", "current_value": "2", "recommended_value": "2", "description": "SSO ticket creation", "compliant": True},
    {"parameter": "snc/enable", "current_value": "0", "recommended_value": "1", "description": "Secure Network Communication", "compliant": False},
]


# ============================================================
# Audit Log
# ============================================================

DEMO_AUDIT_LOG = [
    {"timestamp": (datetime.now() - timedelta(hours=2)).isoformat(), "event_type": "login_failed", "username": "ADMIN01", "terminal": "10.0.1.50", "detail": "Wrong password - attempt 3 of 5", "severity": "Warning"},
    {"timestamp": (datetime.now() - timedelta(hours=5)).isoformat(), "event_type": "login_failed", "username": "J.SMITH", "terminal": "10.0.2.15", "detail": "Wrong password - attempt 1 of 5", "severity": "Info"},
    {"timestamp": (datetime.now() - timedelta(hours=8)).isoformat(), "event_type": "login_failed", "username": "UNKNOWN_USER", "terminal": "192.168.1.100", "detail": "User does not exist", "severity": "Warning"},
    {"timestamp": (datetime.now() - timedelta(hours=12)).isoformat(), "event_type": "auth_change", "username": "ADMIN01", "terminal": "10.0.1.50", "detail": "Role Z_FI_PAYMENT_RUN assigned to J.SMITH", "severity": "High"},
    {"timestamp": (datetime.now() - timedelta(days=1)).isoformat(), "event_type": "auth_change", "username": "ADMIN01", "terminal": "10.0.1.50", "detail": "Profile SAP_ALL assigned to EMERGENCY", "severity": "Critical"},
    {"timestamp": (datetime.now() - timedelta(days=1, hours=3)).isoformat(), "event_type": "user_change", "username": "ADMIN01", "terminal": "10.0.1.50", "detail": "User OLD_VENDOR unlocked", "severity": "Warning"},
    {"timestamp": (datetime.now() - timedelta(days=2)).isoformat(), "event_type": "rfc_call", "username": "RFC_FICO", "terminal": "10.0.3.200", "detail": "RFC call to BAPI_USER_GET_DETAIL from external system", "severity": "Info"},
    {"timestamp": (datetime.now() - timedelta(days=2, hours=6)).isoformat(), "event_type": "login_failed", "username": "ADMIN02", "terminal": "10.0.5.99", "detail": "Wrong password - attempt 5 of 5 - USER LOCKED", "severity": "Critical"},
    {"timestamp": (datetime.now() - timedelta(days=3)).isoformat(), "event_type": "auth_change", "username": "P.MUELLER", "terminal": "10.0.1.80", "detail": "Role Z_MM_PURCHASE_APPROVE removed from R.KUMAR temporarily", "severity": "Info"},
    {"timestamp": (datetime.now() - timedelta(days=3, hours=2)).isoformat(), "event_type": "user_change", "username": "ADMIN01", "terminal": "10.0.1.50", "detail": "New user N.SILVA created", "severity": "Info"},
    {"timestamp": (datetime.now() - timedelta(days=4)).isoformat(), "event_type": "rfc_call", "username": "RFC_FICO", "terminal": "10.0.3.200", "detail": "RFC call to BAPI_COMPANYCODE_GETLIST", "severity": "Info"},
    {"timestamp": (datetime.now() - timedelta(days=5)).isoformat(), "event_type": "login_failed", "username": "EMERGENCY", "terminal": "192.168.1.200", "detail": "Login attempt from unknown IP", "severity": "Critical"},
]


# ============================================================
# RFC Connections
# ============================================================

DEMO_RFC_CONNECTIONS = [
    {"destination": "ECC_PROD", "description": "Production ECC System", "connection_type": "3", "host": "10.0.3.100", "system_number": "00", "client": "100", "stored_credentials": True, "stored_user": "RFC_INTERFACE", "last_used": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d"), "status": "Active"},
    {"destination": "BW_PROD", "description": "Production BW System", "connection_type": "3", "host": "10.0.3.110", "system_number": "00", "client": "100", "stored_credentials": True, "stored_user": "RFC_BW", "last_used": (datetime.now() - timedelta(days=0)).strftime("%Y-%m-%d"), "status": "Active"},
    {"destination": "CRM_PROD", "description": "Production CRM System", "connection_type": "3", "host": "10.0.3.120", "system_number": "00", "client": "200", "stored_credentials": True, "stored_user": "RFC_CRM", "last_used": (datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d"), "status": "Active"},
    {"destination": "PI_PROD", "description": "Process Integration", "connection_type": "3", "host": "10.0.3.130", "system_number": "00", "client": "100", "stored_credentials": False, "stored_user": "", "last_used": (datetime.now() - timedelta(days=0)).strftime("%Y-%m-%d"), "status": "Active"},
    {"destination": "SOLMAN", "description": "Solution Manager", "connection_type": "3", "host": "10.0.3.140", "system_number": "01", "client": "100", "stored_credentials": False, "stored_user": "", "last_used": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"), "status": "Active"},
    {"destination": "LEGACY_ERP", "description": "Legacy ERP System (Decommissioned)", "connection_type": "3", "host": "10.0.5.50", "system_number": "00", "client": "100", "stored_credentials": True, "stored_user": "OLD_RFC", "last_used": (datetime.now() - timedelta(days=180)).strftime("%Y-%m-%d"), "status": "Error"},
    {"destination": "HTTP_BANK", "description": "Bank Interface HTTP", "connection_type": "H", "host": "https://api.bank-demo.com", "system_number": "", "client": "", "stored_credentials": True, "stored_user": "BANK_API", "last_used": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d"), "status": "Active"},
]


# ============================================================
# SoD Violations
# ============================================================

DEMO_SOD_VIOLATIONS = [
    {"username": "J.SMITH", "full_name": "John Smith", "department": "Finance",
     "function1": "Create Vendor Invoice", "function2": "Approve Payment Run",
     "risk_level": "Critical", "risk_id": "SOD-FI-001",
     "business_impact": "User can create fraudulent invoices and approve their own payments",
     "roles_causing_conflict": ["Z_FI_ACCOUNTS_PAYABLE", "Z_FI_PAYMENT_RUN"]},
    {"username": "J.SMITH", "full_name": "John Smith", "department": "Finance",
     "function1": "Post Vendor Invoice", "function2": "Post Customer Credit",
     "risk_level": "High", "risk_id": "SOD-FI-002",
     "business_impact": "User can manipulate both payable and receivable ledgers",
     "roles_causing_conflict": ["Z_FI_ACCOUNTS_PAYABLE", "Z_FI_ACCOUNTS_RECEIVABLE"]},
    {"username": "R.KUMAR", "full_name": "Raj Kumar", "department": "Procurement",
     "function1": "Create Purchase Order", "function2": "Approve Purchase Order",
     "risk_level": "Critical", "risk_id": "SOD-MM-001",
     "business_impact": "User can create and self-approve purchase orders",
     "roles_causing_conflict": ["Z_MM_PURCHASER", "Z_MM_PURCHASE_APPROVE"]},
    {"username": "R.KUMAR", "full_name": "Raj Kumar", "department": "Procurement",
     "function1": "Create Purchase Order", "function2": "Goods Receipt",
     "risk_level": "High", "risk_id": "SOD-MM-002",
     "business_impact": "User can order goods and confirm receipt without verification",
     "roles_causing_conflict": ["Z_MM_PURCHASER", "Z_MM_GOODS_RECEIPT"]},
    {"username": "S.WILSON", "full_name": "Sarah Wilson", "department": "HR",
     "function1": "Maintain HR Master Data", "function2": "Process Payroll",
     "risk_level": "Critical", "risk_id": "SOD-HR-001",
     "business_impact": "User can create ghost employees and process their payroll",
     "roles_causing_conflict": ["Z_HR_ADMIN", "Z_HR_PAYROLL"]},
    {"username": "A.PATEL", "full_name": "Anita Patel", "department": "Controlling",
     "function1": "Post GL Entries", "function2": "Cost Center Allocation",
     "risk_level": "High", "risk_id": "SOD-CO-001",
     "business_impact": "User can post journal entries and reallocate costs without oversight",
     "roles_causing_conflict": ["Z_FI_GL_POSTING", "Z_CO_COST_CENTER"]},
    {"username": "OLD_VENDOR", "full_name": "Legacy Vendor Account", "department": "External",
     "function1": "View Purchase Orders", "function2": "Create Purchase Orders",
     "risk_level": "High", "risk_id": "SOD-MM-003",
     "business_impact": "External vendor account has both read and write access to purchasing",
     "roles_causing_conflict": ["Z_MM_VENDOR_PORTAL", "Z_MM_PURCHASER"]},
]


# ============================================================
# Transport Log
# ============================================================

DEMO_TRANSPORT_LOG = [
    {"transport_id": "S4HK900001", "description": "FI - New payment block reason", "type": "Customizing", "owner": "J.SMITH", "status": "Imported", "created": (datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d"), "imported": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")},
    {"transport_id": "S4HK900002", "description": "MM - Purchase order approval workflow", "type": "Workbench", "owner": "L.CHEN", "status": "Released", "created": (datetime.now() - timedelta(days=5)).strftime("%Y-%m-%d"), "imported": None},
    {"transport_id": "S4HK900003", "description": "HR - Payroll schema changes", "type": "Workbench", "owner": "L.CHEN", "status": "Imported", "created": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"), "imported": (datetime.now() - timedelta(days=4)).strftime("%Y-%m-%d")},
    {"transport_id": "S4HK900004", "description": "SD - Pricing condition table", "type": "Customizing", "owner": "ADMIN01", "status": "Imported", "created": (datetime.now() - timedelta(days=10)).strftime("%Y-%m-%d"), "imported": (datetime.now() - timedelta(days=8)).strftime("%Y-%m-%d")},
    {"transport_id": "S4HK900005", "description": "Basis - Security audit log config", "type": "Customizing", "owner": "ADMIN01", "status": "Imported", "created": (datetime.now() - timedelta(days=14)).strftime("%Y-%m-%d"), "imported": (datetime.now() - timedelta(days=12)).strftime("%Y-%m-%d")},
    {"transport_id": "S4HK900006", "description": "FI - New GL account assignments", "type": "Customizing", "owner": "M.JONES", "status": "Released", "created": (datetime.now() - timedelta(days=2)).strftime("%Y-%m-%d"), "imported": None},
    {"transport_id": "S4HK900007", "description": "ABAP - Custom report Z_SEC_CHECK", "type": "Workbench", "owner": "L.CHEN", "status": "Imported", "created": (datetime.now() - timedelta(days=20)).strftime("%Y-%m-%d"), "imported": (datetime.now() - timedelta(days=18)).strftime("%Y-%m-%d")},
]


# ============================================================
# Authorization Trace
# ============================================================

DEMO_AUTH_TRACE = [
    {"timestamp": (datetime.now() - timedelta(hours=1)).isoformat(), "username": "J.SMITH", "transaction": "FB60", "auth_object": "F_BKPF_BUK", "field": "BUKRS", "value": "1000", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=1, minutes=5)).isoformat(), "username": "J.SMITH", "transaction": "F110", "auth_object": "F_REGU_BUK", "field": "BUKRS", "value": "1000", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=2)).isoformat(), "username": "R.KUMAR", "transaction": "ME21N", "auth_object": "M_BEST_BSA", "field": "BSART", "value": "NB", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=2, minutes=10)).isoformat(), "username": "R.KUMAR", "transaction": "ME29N", "auth_object": "M_EINK_FRG", "field": "EKGRP", "value": "001", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=3)).isoformat(), "username": "S.WILSON", "transaction": "PA30", "auth_object": "P_ORGIN", "field": "INFTY", "value": "0001", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=3, minutes=30)).isoformat(), "username": "M.JONES", "transaction": "FB50", "auth_object": "F_BKPF_BUK", "field": "BUKRS", "value": "1000", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=4)).isoformat(), "username": "D.BROWN", "transaction": "VA01", "auth_object": "V_VBAK_VKO", "field": "VKORG", "value": "1000", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=5)).isoformat(), "username": "L.CHEN", "transaction": "SE38", "auth_object": "S_DEVELOP", "field": "DEVCLASS", "value": "ZLOCAL", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=5, minutes=15)).isoformat(), "username": "L.CHEN", "transaction": "SE80", "auth_object": "S_DEBUG", "field": "ACTVT", "value": "03", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=6)).isoformat(), "username": "N.SILVA", "transaction": "FB60", "auth_object": "F_BKPF_BUK", "field": "BUKRS", "value": "2000", "result": "FAIL"},
    {"timestamp": (datetime.now() - timedelta(hours=6, minutes=5)).isoformat(), "username": "N.SILVA", "transaction": "FB60", "auth_object": "F_BKPF_BUK", "field": "BUKRS", "value": "1000", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=7)).isoformat(), "username": "ADMIN01", "transaction": "SU01", "auth_object": "S_USER_GRP", "field": "ACTVT", "value": "02", "result": "PASS"},
    {"timestamp": (datetime.now() - timedelta(hours=8)).isoformat(), "username": "P.MUELLER", "transaction": "SUIM", "auth_object": "S_USER_GRP", "field": "ACTVT", "value": "03", "result": "PASS"},
]
